version: "2.1"

services:
  web:
    restart: always
    container_name: web
    env_file:
      - ./config/production.env
    volumes:
       - /var/assignment-dashboard/sqlite:/app/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  worker:
    restart: always
    build: worker
    container_name: worker
    env_file:
      - ./config/production.env
    volumes:
       - /var/assignment-dashboard/sqlite:/app/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  nginx:
    container_name: nginx
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"

  redis:
    restart: always
    container_name: redis
    volumes:
      - /var/assignment-dashboard/redis:/data
