version: "2.1"

services:
  web:
    build:
      context: .
    image: assignment-dashboard
    container_name: assignment-dashboard
    environment:
      - FLASK_DEBUG
      - GITHUB_API_TOKEN
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - SECRET_KEY
      - SQLALCHEMY_ECHO
      - TZ
    ports:
      - 5000:5000
