version: "2.1"

services:
  flask:
    build:
      context: .
    image: assignment-dashboard
    container_name: assignment-dashboard
    environment:
      - GITHUB_API_TOKEN
    ports:
      - 5000:5000
    volumes:
       - .:/app
