version: "2.1"

services:
  web:
    container_name: web
    env_file:
      - ./config/production.env
    volumes:
       - /var/local:/app/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  nginx:
    container_name: nginx
    logging:
      options:
        max-size: 10m
        max-file: "3"
