version: "2.1"

services:
  web:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:9.6.1
    healthcheck:
      test: "psql -U postgres -c '\\l';"
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres:
