version: "2.1"

services:
  web:
    build: .
    image: assignment-dashboard
    # the default override publishes port 5000
    # the production override expose this port internally

  nginx:
    build: nginx/
    ports:
      - 80:80
